package database;
// Generated 14 dic 2025, 16:25:19 by Hibernate Tools 6.5.1.Final

/**
 * Dept2 generated by hbm2java
 */
public class Dept2 implements java.io.Serializable {

	private int deptno2;
	private String dname2;
	private String loc2;

	public Dept2() {
	}

	public Dept2(int deptno2, String dname2) {
		this.deptno2 = deptno2;
		this.dname2 = dname2;
	}

	public Dept2(int deptno2, String dname2, String loc2) {
		this.deptno2 = deptno2;
		this.dname2 = dname2;
		this.loc2 = loc2;
	}

	public int getDeptno2() {
		return this.deptno2;
	}

	public void setDeptno2(int deptno2) {
		this.deptno2 = deptno2;
	}

	public String getDname2() {
		return this.dname2;
	}

	public void setDname2(String dname2) {
		this.dname2 = dname2;
	}

	public String getLoc2() {
		return this.loc2;
	}

	public void setLoc2(String loc2) {
		this.loc2 = loc2;
	}

}
