-- Datos limpios de bibliotecas (sin duplicados ni entradas incompletas)
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca Central', 'Calle Mayor 12', 'Madrid', 1954);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca Sur Actualizada', 'Calle Sol 99', 'Valencia', 1990);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca Inconsistente', 'Calle Error 1', 'ErrorCity', 2000);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca Cervantes', 'Calle Quijote 99', 'Toledo', 1949);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Río', 'Av. Guadalquivir 19', 'Sevilla', 1971);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca de la Ciencia', 'Calle Newton 14', 'Granada', 1990);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Este', 'Av. Horizonte 5', 'Murcia', 1982);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Oeste', 'Calle Luna 7', 'Cádiz', 1938);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca Vega Baja', 'Av. Palmeras 10', 'Alicante', 2001);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Prado', 'Calle Arte 9', 'Málaga', 1968);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca Horizonte', 'Av. Montaña 33', 'Zaragoza', 1975);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Viento', 'Calle Aire 2', 'Burgos', 1957);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Saber', 'Calle Estudio 11', 'Salamanca', 1924);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Puerto', 'Muelle 4', 'Santander', 1989);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca Atlántica', 'Av. Faro 18', 'Vigo', 1995);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Norte', 'Calle Roble 6', 'Oviedo', 1973);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Sur', 'Av. Jardines 21', 'Huelva', 1981);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Castillo', 'Calle Muralla 15', 'Ávila', 1942);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca Imperial', 'Plaza Mayor 1', 'Segovia', 1931);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Parque', 'Calle Verde 8', 'Pamplona', 1999);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Alba', 'Av. Amanecer 12', 'Logroño', 1984);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Valle', 'Calle Prado 17', 'León', 1950);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Roble', 'Av. Bosque 3', 'Soria', 1976);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Mirador', 'Calle Vista 20', 'Cuenca', 1965);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Centro', 'Plaza España 9', 'Valladolid', 1987);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Horizonte', 'Calle Cima 14', 'Bilbao', 1993);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Encinar', 'Av. Encina 7', 'Cáceres', 1970);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Tajo', 'Calle Río 5', 'Talavera', 1988);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Albaicín', 'Calle Albaicín 2', 'Granada', 1935);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Mediterráneo', 'Paseo Marítimo 30', 'Castellón', 2003);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Olivar', 'Calle Olivo 13', 'Jaén', 1961);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Camino', 'Av. Peregrino 9', 'Badajoz', 1992);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Ebro', 'Calle Río 10', 'Tudela', 1980);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Arco', 'Plaza Arco 4', 'Córdoba', 1947);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Sol', 'Calle Amanecer 6', 'Almería', 1997);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Faro', 'Av. Costa 22', 'Gijón', 2005);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Prado Verde', 'Calle Jardín 11', 'Lugo', 1974);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Encanto', 'Calle Magia 3', 'Teruel', 1969);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Alba Dorada', 'Av. Oro 18', 'Zamora', 1956);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Horizonte Azul', 'Calle Cielo 7', 'Huesca', 1986);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Robledal', 'Av. Robles 15', 'Ourense', 1991);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Mirador Norte', 'Calle Altura 9', 'Béjar', 1972);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Castillo Real', 'Plaza Castillo 1', 'Medina del Campo', 1933);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Río Grande', 'Calle Agua 16', 'Albacete', 1983);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Alba Serena', 'Av. Serenidad 12', 'Guadalajara', 1994);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Puente', 'Calle Puente 5', 'Ronda', 1955);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Horizonte Verde', 'Av. Bosque 20', 'Ponferrada', 2002);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Alba Norte', 'Calle Aurora 8', 'Santiago de Compostela', 1979);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca del Mar Interior', 'Paseo Lago 14', 'Vitoria', 1964);
INSERT INTO biblioteca(nombre, direccion, ciudad, anio_fundacion) VALUES('Biblioteca Moderna', 'Av. Futuro 10', 'Valencia', 2023);