#Propiedades de libros - No modificar manualmente
#Sun Feb 08 16:48:30 CET 2026
anio=1967
autor=Gabriel Garc\u00EDa M\u00E1rquez
idioma=espa\u00F1ol
paginas=471
titulo=Cien a\u00F1os de soledad
