package database;
// Generated 14 dic 2025, 16:25:19 by Hibernate Tools 6.5.1.Final

/**
 * Bonus generated by hbm2java
 */
public class Bonus implements java.io.Serializable {

	private BonusId id;

	public Bonus() {
	}

	public Bonus(BonusId id) {
		this.id = id;
	}

	public BonusId getId() {
		return this.id;
	}

	public void setId(BonusId id) {
		this.id = id;
	}

}
