package database;
// Generated 14 dic 2025, 16:25:19 by Hibernate Tools 6.5.1.Final

/**
 * BonusId generated by hbm2java
 */
public class BonusId implements java.io.Serializable {

	private Integer comm;
	private String ename;
	private String job;
	private Integer sal;

	public BonusId() {
	}

	public BonusId(Integer comm, String ename, String job, Integer sal) {
		this.comm = comm;
		this.ename = ename;
		this.job = job;
		this.sal = sal;
	}

	public Integer getComm() {
		return this.comm;
	}

	public void setComm(Integer comm) {
		this.comm = comm;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public Integer getSal() {
		return this.sal;
	}

	public void setSal(Integer sal) {
		this.sal = sal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BonusId))
			return false;
		BonusId castOther = (BonusId) other;

		return ((this.getComm() == castOther.getComm()) || (this.getComm() != null && castOther.getComm() != null
				&& this.getComm().equals(castOther.getComm())))
				&& ((this.getEname() == castOther.getEname()) || (this.getEname() != null
						&& castOther.getEname() != null && this.getEname().equals(castOther.getEname())))
				&& ((this.getJob() == castOther.getJob()) || (this.getJob() != null && castOther.getJob() != null
						&& this.getJob().equals(castOther.getJob())))
				&& ((this.getSal() == castOther.getSal()) || (this.getSal() != null && castOther.getSal() != null
						&& this.getSal().equals(castOther.getSal())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getComm() == null ? 0 : this.getComm().hashCode());
		result = 37 * result + (getEname() == null ? 0 : this.getEname().hashCode());
		result = 37 * result + (getJob() == null ? 0 : this.getJob().hashCode());
		result = 37 * result + (getSal() == null ? 0 : this.getSal().hashCode());
		return result;
	}

}
